# Generated by Django 3.1.4 on 2021-02-13 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='دسته بندی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sub', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=30, verbose_name='برچسب')),
            ],
            options={
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='LabelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.label', verbose_name='برچسب')),
            ],
            options={
                'verbose_name_plural': 'برچسب های پست',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=30, verbose_name='نام مستعار')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='عکس پست')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='زمان ایجاد پست')),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=30, verbose_name='زمان بروزرسانی پست')),
                ('activation', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('verification', models.BooleanField(default=False, verbose_name='تایید کردن محتوای پست')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی')),
                ('dislikes', models.ManyToManyField(blank=True, null=True, related_name='blog_disliked_posts', related_query_name='blog_disliked_posts', to=settings.AUTH_USER_MODEL)),
                ('labelpost', models.ManyToManyField(through='blog.LabelPost', to='blog.Label')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='blog_liked_posts', related_query_name='blog_liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'پست ها',
                'permissions': (('can_verify', 'Can verify post'), ('can_unverify', 'Can unverify post')),
            },
        ),
        migrations.AddField(
            model_name='labelpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.post', verbose_name='پست'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.CharField(max_length=30, verbose_name='زمان انتشار')),
                ('verification', models.BooleanField(default=False, verbose_name='تایید کردن محتوای نظر')),
                ('dislikes', models.ManyToManyField(blank=True, null=True, related_name='blog_disliked_comments', related_query_name='blog_disliked_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='blog_liked_comments', related_query_name='blog_liked_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
