# Generated by Django 3.1.4 on 2021-01-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='دسته بندی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=30, verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='LabelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.label', verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_number', models.IntegerField(default=0, verbose_name='پسندیدن')),
                ('dislike_number', models.IntegerField(default=0, verbose_name='نپسندیدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس پروفایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('text', models.TextField(max_length=1000, verbose_name='متن')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس پست')),
                ('pub_date', models.CharField(max_length=30, verbose_name='زمان انتشار')),
                ('activation', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('verification', models.BooleanField(default=False, verbose_name='تایید کردن محتوای پست')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی')),
                ('labelpost', models.ManyToManyField(through='blog.LabelPost', to='blog.Label')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.like', verbose_name='پسندیدن/نپسندیدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='labelpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.post', verbose_name='پست'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('date', models.CharField(max_length=30, verbose_name='زمان انتشار')),
                ('verification', models.BooleanField(default=False, verbose_name='تایید کردن محتوای نظر')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.like', verbose_name='پسندیدن/نپسندیدن')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
