# Generated by Django 3.1.4 on 2021-02-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210214_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='images/default-avatar.jpg', upload_to='images/', verbose_name='عکس پروفایل'),
        ),
    ]
