# Generated by Django 3.1.4 on 2021-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.BooleanField(default=False, verbose_name='ذخیره کردن'),
        ),
    ]
