# Generated by Django 3.1.4 on 2021-02-16 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_post_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='star',
        ),
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_star', to=settings.AUTH_USER_MODEL, verbose_name='ذخیره کردن'),
        ),
    ]
