# Generated by Django 3.1.4 on 2021-02-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210216_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_pub',
            field=models.DateTimeField(auto_now=True, max_length=30, verbose_name='زمان انتشار'),
        ),
    ]
