# Generated by Django 3.1.4 on 2021-02-20 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210218_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'نظرات'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_pub',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='verification',
            new_name='verificated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='activation',
            new_name='activated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='verification',
            new_name='verificated',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=30, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
    ]
