# Generated by Django 3.1.4 on 2021-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210303_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='default/default-avatar.jpg', upload_to='images/', verbose_name='عکس پروفایل'),
        ),
    ]
